import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by running the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :ai_brand_agent, AiBrandAgentWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# `force_ssl` is set in `config/runtime.exs` only (prod block), so it can follow
# PHX_PUBLIC_SCHEME (http UAT vs https behind nginx) without compile/runtime mismatch.

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done in config/runtime.exs.
