defmodule AiBrandAgent.Accounts.Post do
  @moduledoc """
  A social media post — generated by ContentAgent, published by PostAgent.

  ## Status lifecycle

      draft → approved → publishing → published
                                    ↘ failed
  """

  use Ecto.Schema
  import Ecto.Changeset

  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id

  @statuses ~w(draft approved scheduled publishing published failed discarded)

  schema "posts" do
    field :platform, :string
    field :content, :string
    field :status, :string, default: "draft"
    field :platform_post_id, :string
    field :published_at, :utc_datetime
    field :error_message, :string
    field :variant_index, :integer
    field :style_tag, :string
    field :draft_ready_email_sent_at, :utc_datetime

    belongs_to :user, AiBrandAgent.Accounts.User
    belongs_to :topic, AiBrandAgent.Accounts.Topic
    belongs_to :generation_run, AiBrandAgent.Accounts.PostGenerationRun

    timestamps(type: :utc_datetime)
  end

  def changeset(post, attrs) do
    post
    |> cast(attrs, [
      :platform,
      :content,
      :status,
      :platform_post_id,
      :published_at,
      :error_message,
      :user_id,
      :topic_id,
      :generation_run_id,
      :variant_index,
      :style_tag,
      :draft_ready_email_sent_at
    ])
    |> validate_required([:platform, :content, :status, :user_id])
    |> validate_inclusion(:platform, ["linkedin", "facebook"])
    |> validate_inclusion(:status, @statuses)
    |> foreign_key_constraint(:user_id)
    |> foreign_key_constraint(:topic_id)
  end

  def status_changeset(post, status, extra_attrs \\ %{}) do
    attrs = Map.merge(%{status: status}, extra_attrs)

    post
    |> cast(attrs, [:status, :platform_post_id, :published_at, :error_message])
    |> validate_inclusion(:status, @statuses)
  end
end
